### ISSUE TITLE
Request = format document Shift+alt + A

### ISSUE THREAD

**Issue by ericcobblepot** [m7bellei/otui-otmd-code-extension#3]
maybe they could put "format document Shift+alt + A "

![image](https://github.com/m7bellei/otui-otmd-code-extension/assets/125500615/d7e347eb-ca0c-471e-b875-958b2bef620a)

would fix tab problems, line breaks, etc.

**Comment by mateusbellei** [comment]
interesting! nice idea @ericcobblepot I'll do it on 1.2.0
